#!/usr/bin/env python

"""
Lifted and reworked from https://github.com/danielgtaylor/guid-tool
Convert a UUID from various forms to uppercase GUID string. Can take input as a base64-encoded
string, and integer, or the hex string representation. Outputs all three
back to the terminal.
"""

import base64
import uuid

from optparse import OptionParser

parser = OptionParser(**{
    'usage': 'Usage: %prog [options] [GUID]',
    'version': '1.0'
})

options, args = parser.parse_args()

#print(str(args))

if not len(args):
    exit()
else:
    if args[0].isdigit():
        guid = uuid.UUID(int=int(args[0]))
    elif len(args[0]) == 24:
       guid = uuid.UUID(bytes_le=base64.b64decode(args[0]))
    else:
        guid = uuid.UUID(args[0])

print(str(guid).upper())